- docs/_meta.json
This reverts commit 0e32e036c62a39835b3274be9b6da0263e9c41e6.
> Revert "Update _meta.json"

- .github/workflows/deploy.yml
- proxy/bin/buildAssets.ts
- proxy/bin/buildContributors.ts
- proxy/bin/fetchContributors.ts
- proxy/bun.lock
- proxy/package.json
- proxy/src/index.ts
- proxy/src/routes/index.ts
- proxy/src/types.d.ts
- proxy/src/utils/fetchMenuItems.ts
- proxy/src/utils/getPageUrl.ts
- Fetch contributors on merge/deploy
- Serve contributors from disk
> Fetch contributors at build/deploy time

- docs/01-about/index.md
Renamed about page
Please delete options that are not relevant.
> Renamed about page

- docs/15-connecting-data/02-working-with-apis/index.md
- docs/15-connecting-data/04-authentication/index.md
Changed the connecting data section according to Erik's notes.
Fixes # (issue number, if applicable)
Please check the options that are relevant:
Before submitting your PR, please confirm that:
> Added review for connecting data section

- docs/07-styling/03-styles-and-layout/index.md
- docs/08-pages/01-overview/index.md
- Added missing reference in pages/overview to connecting-data/overview
- Fixed weird line break in long link in styling/styles-and-layout
Please check the options that are relevant:
Before submitting your PR, please confirm that:
> Line break fixes and missing reference

- proxy/src/index.ts
This allows the docs to serve a relevant sitemap.xml file. I've not added <priority> or <lastmod> tags yet.
> Add sitemap.xml endpoint to proxy

- proxy/src/routes/fetchContent.ts
Changed default owner from "toddledev" to "nordcraftengine" to load docs content fast on the default repo.
Please check the options that are relevant:
Before submitting your PR, please confirm that:
> Updated default owner for preferLocalContent

- proxy/src/index.ts
- proxy/src/routes/fetchContent.ts
- proxy/src/routes/fetchMenu.ts
- proxy/src/routes/index.ts
- proxy/src/types.d.ts
- proxy/src/utils/helpers.ts
Added routine the the worker proxy for fetching the menu. This is in preparation to separating menu and content API calls in the docs frontend
> Added dedicated route for fetching the menu

- proxy/src/routes/fetchContent.ts
Removed the menu items from the /content route to reduce transfer size.
> Removed menu items from content route response

- proxy/src/routes/fetchMenu.ts
Fixes a linter error encountered when creating new PRs.
> Fix lintter error

- docs/12-workflows/03-recursive-workflows/index.md
- Adjusted recursive workflows index.md
- [x ] Documentation update (typo fixes, improved clarity, etc.)
- [ x] My changes follow the formatting guidelines in the contribution guide
- [ x] I have performed a self-review of my changes
- [ x] I have tested all links to ensure they point to valid pages
- [ x] I have verified that images display correctly
- [ x] I have checked examples (if applicable) to ensure they work correctly
- [ x] I have used consistent terminology throughout the documentation
- [ x] I have placed content in the correct numbered folders to maintain proper ordering
- [ x] I have checked my changes for spelling and grammatical errors
> recursive workflows adjusted

- CONTRIBUTING.md
- docs/18-guides/99-contribution/index.md
1. The markdown has been formatted correctly to avoid markdown linters complaining. I have confirmed that this does not break anything to do with layout. There is now only one H1 on this page as prescribed in the contributing guidelines.
2. Some wording has been changed to make things clearer, such as changing some of the guidelines to specifically 'Do not'.
> Update contributing guidelines

- docs/02-use-cases/index.md
This PR makes some changes to the use cases page, in particular a couple of callouts, and some expanding on the use cases lists.
Review the changes on the FE here: https://docs.nordcraft.com/use-cases?mode=preview&owner=nordcraftengine&repository=documentation&branch=update-use-cases
> Update use cases

- docs/01-about/index.md
This PR adds some updates to the about page, to make it really POP.
Review changes here: https://docs.nordcraft.com/about?mode=preview&owner=nordcraftengine&branch=update-about&repository=documentation
> Update about page

- docs/03-core-concepts/index.md
This PR makes some edits to the core concepts page.
Review on the FE: https://docs.nordcraft.com/core-concepts?mode=preview&owner=nordcraftengine&repository=documentation&branch=update-core-concepts
> Update core concepts

- docs/04-get-started/01-overview/index.md
- docs/04-get-started/02-create-a-project/index.md
- docs/04-get-started/03-project-details/index.md
- docs/04-get-started/04-branches-and-publishing/index.md
This PR updates all of the sections under 'Get started'.
Preview on the FE: https://docs.nordcraft.com/get-started/overview?mode=preview&owner=nordcraftengine&repository=documentation&branch=update-get-started
> Update get started

- .github/workflows/test.yml
- README.md
- bun.lock
- eslint.config.mjs
- package.json
- proxy/bun.lock
- proxy/package.json
See https://github.com/eslint/markdown
> Add eslint checking of markdown files

- docs/06-building-blocks/01-pages/index.md
- docs/06-building-blocks/02-elements/index.md
- docs/06-building-blocks/03-components/index.md
This PR makes a few changes to the copy in the build blocks section.
> Update building blocks sections

- docs/05-the-editor/09-element-panel/index.md
- docs/05-the-editor/10-shortcuts/index.md
- docs/07-styling/01-default-styles/index.md
- docs/07-styling/02-theme/index.md
- docs/07-styling/03-styles-and-layout/index.md
- docs/07-styling/04-conditional-styles/index.md
This PR updates the styling section.
> Update styling section

- docs/08-pages/01-overview/index.md
- docs/08-pages/02-create-a-page/index.md
- docs/08-pages/03-page-configuration/index.md
- docs/08-pages/04-static-and-dynamic/index.md
This PR updates the pages section.
> Update pages section

- docs/12-workflows/01-overview/index.md
Added a section about sequential execution of nodes in a workflow. Whether the noes in a workflow execute sequentially is a question that has come up a few times in our discord. So I thought it would be good to add an explainer here in the docs.
- [NA] I have tested all links to ensure they point to valid pages
- [NA] I have verified that images display correctly
- [NA] I have checked examples (if applicable) to ensure they work correctly
NA
NA
This is my very first pull request on github. If I did anything in the wrong manner, I apologise. I have tried to follow all the instructions.
> Add section on sequential execution of nodes in workflows -> Update 12-workflows 01-overview index.md

- docs/09-components/01-overview/index.md
- docs/09-components/02-create-a-component/index.md
- docs/09-components/03-interface-and-lifecycle/index.md
- docs/09-components/04-compositions/index.md
- docs/09-components/05-export-a-component/index.md
This PR updates the content in the components section.
> Update components section

- docs/10-variables/01-overview/index.md
- docs/10-variables/02-working-with-variables/index.md
This PR updates the variables section.
> Update variables section

- docs/11-formulas/01-overview/index.md
- docs/11-formulas/02-working-with-formulas/index.md
- docs/11-formulas/03-show-hide-formula/index.md
- docs/11-formulas/04-repeat-formula/index.md
- docs/11-formulas/05-global-formulas/index.md
This PR updates the formulas section.
> Update formulas section

- docs/13-contexts/01-overview/index.md
- docs/13-contexts/02-working-with-contexts/index.md
This PR updates the contexts section.
> Update working with contexts

- docs/01-about/index.md
- docs/02-use-cases/index.md
- docs/03-core-concepts/index.md
- docs/15-connecting-data/01-overview/index.md
- docs/15-connecting-data/02-working-with-apis/index.md
- docs/15-connecting-data/03-call-an-api/index.md
- docs/15-connecting-data/04-authentication/index.md
- docs/15-connecting-data/05-streaming/index.md
- docs/15-connecting-data/06-advanced-api-features/index.md
- docs/15-connecting-data/07-services/index.md
- docs/18-guides/99-contribution/index.md
This PR updates the connecting data section.
> Update connecting data section

- docs/16-packages/01-overview/index.md
- docs/16-packages/02-managing-packages/index.md
- docs/16-packages/03-creating-and-launching/index.md
This PR updates the packages section.
> Update packages content

- docs/17-good-practices/01-branching/index.md
- docs/18-guides/01-component-creation/index.md
This PR updates good practises and the documentation on when to create a component.
> Update good practises

- bun.lock
- package.json
- proxy/bun.lock
- proxy/package.json
Bump:
- hono
- marked
- Cloudflare + node types
- wrangler
To test: 
`bun run dev` locally and check a few endpoints work - for example:
- http://localhost:9000/content/toddledev/documentation/main/the-editor/canvas
- http://localhost:9000/video-thumbnail/ulZJTV3ouHs
> Bump dependencies

- proxy/bin/libReferences/actions/actions.ts
- proxy/bin/libReferences/formulas/formulas.ts
To better avoid situations like this one https://github.com/nordcraftengine/nordcraft/pull/282
> Avoid undefined actions and formulas descriptions

- bun.lock
- proxy/package.json
Tested it locally, and it works fine.
> Bump wrangler and types

- bun.lock
- docs/19-references/02-actions/index.md
I got confused with actions and custom actions, so hopefully this provides clarity.
> Add clarity on where Actions are available to use

- docs/18-guides/99-contribution/index.md
> Two small grammar fixes

- bun.lock
- package.json
- proxy/package.json
- proxy/src/routes/search.ts
Closes #222
This PR makes the search results more accurate by allowing fewer typos.
I've also bumped all dependencies.
> Allow fewer typos in search results

- docs/05-the-editor/02-canvas/index.md
- docs/05-the-editor/10-shortcuts/index.md
Add short documentation on the canvas drag and drop feature.
Fixes #216
> Drag and drop

- README.md
- docs/01-about/index.md
- docs/18-guides/99-contribution/index.md
Some small updates to the README and about page to cross-reference the nordcraft engine.
> Add open source info for nordcraft to readme and about page

- docs/01-about/index.md
- docs/02-use-cases/index.md
- docs/03-core-concepts/index.md
- docs/05-the-editor/07-issues-panel/index.md
- docs/15-connecting-data/02-working-with-apis/index.md
- docs/19-references/01-formulas/index.md
- modified about/index.md
- modified use-cases/index.md
- modified references/formulas/index.md
- modified core-concepts/index.md
- modified the-editor/issues-panel/index.md
- modified connecting-data/working-with-apis/index.md
Have made the descriptions concise, retaining the meaning and keywords for SEO optimisation. Also kept the description under 150 words so that its not too long.
Refer the issue [here](https://github.com/nordcraftengine/documentation/issues/235)
> Meta Descriptions According to Ahrefs, Updated Documentation Description

- .github/dependabot.yml
See similar PR here https://github.com/nordcraftengine/nordcraft/pull/341
> Adjust dependabot and add groups for dependencies

- docs/11-formulas/03-show-hide-formula/index.md
Fixed issue where the Dev callout would take over the whole page https://docs.nordcraft.com/formulas/show-hide-formula
> Fixed broken DEV callout

- .github/dependabot.yml
- .github/workflows/test.yml
- proxy/.gitignore
- proxy/bin/buildSitemap.ts
- proxy/package.json
- proxy/src/index.ts
- proxy/wrangler.jsonc
Instead of generating the sitemap dynamically, we can generate it at build time and add a lastModified field to each entry based on git's last commit date for that file.
> Generate static sitemap on build+add lastModified

- proxy/README.md
This adds a README to the proxy folder to better explain its functionality.
@erik-beus This README was largely AI-generated, with some additions by me. Please check it is all accurate and correct.
>  Add proxy README

- .github/workflows/test.yml
- bun.lock
- docs/03-core-concepts/index.md
- proxy/package.json
- proxy/src/utils/fetchPageData.ts
- proxy/src/utils/frontMatter.test.ts
- proxy/src/utils/frontMatter.ts
- proxy/tsconfig.json
Remove the `front-matter` dependency and use custom regexes for parsing front matter.
> Use regex for parsing front matter for md files\*\*

- proxy/bin/createSearchIndex.ts
> Include list items in search index

- docs/02-use-cases/index.md
> Removed duplicate word "and" in info panel

- docs/10-variables/02-working-with-variables/index.md
This PR adds some guidance about adding manual on-change events for variable updates with certain form input types.
> Add guidance re: binding for select, checkbox and radio inputs

- docs/16-packages/03-creating-and-launching/index.md
This PR updates to the active voice and adds some extra guidance on creating packages.
> Add extra package guidance

- docs/15-connecting-data/04-authentication/index.md
Closes https://github.com/nordcraftengine/documentation/issues/185
> Update links to browser extensions

- docs/01-about/index.md
This PR adds clearer information about who Nordcraft is for.
> Update about page to reflect who Nordcraft is for

- docs/04-learn-nordcraft/index.md
This PR adds the Learn Nordcraft lesson 1 video to the Learn Nordcraft page.
> Add lesson 1 to learn page

- docs/04-learn-nordcraft/index.md
This adds Lesson 3 to Learn Norcraft.
> Add lesson 3 video

- docs/20-guides/50-datocms/index.md
2 URLs were pointing to the wrong path.
> Fix relative URLs in DatoCMS guide

- docs/17-connecting-data/07-services/index.md
- docs/18-packages/01-overview/index.md
This adds some info about Nordbase and Supabase Connect.
> Add Supabase connect and Nordbase info

- docs/09-pages/05-redirects/index.md
- docs/09-pages/06-proxies/index.md
- docs/20-guides/50-datocms/index.md
This updates three meta descriptions that were too short, as reported by ahrefs.
> Increase length of 3 meta descriptions

- docs/03-app-examples/index.md
A little update that I thought I had pushed but I hadn't.
> Here is a commit I forgot to put into the last branch

- docs/07-get-started/03-project-details/index.md
- docs/13-media/01-overview/index.md
In an attempt to avoid confusion about media deletion, I've tried to change the severify of our tips reg. project/media deletion. See conversation here https://discord.com/channels/972416966683926538/1405283913584083147
> Clarify media deletion on project deletion

- proxy/bin/buildAssets.ts
- proxy/bin/buildSitemap.ts
- proxy/bin/fileTree.ts
- proxy/src/types.d.ts
- proxy/src/utils/fetchMenuItems.ts
- proxy/src/utils/fetchPageData.ts
After changing how we structure files (and use an index.json file), we could no longer preview branches. This fixes that.
To test, visit these urls:
- http://localhost:9000/content/nordcraftengine/documentation/main/about
- http://localhost:9000/content/nordcraftengine/documentation/test/about
And try to run the docs project against localhost.
> Support using a remote files structure

- proxy/bin/createSearchIndex.ts
Also exit if search index creation fails to fail in CI
Closes #426
> Only process valid tokens for search index

- docs/pages/page-configuration/index.md
- eslint.config.mjs
See https://discord.com/channels/972416966683926538/1422197849998757989
> Adjust head elements section
